### ISSUE TITLE
problem starting a1111 because of tqdm error when installing temporalkit

### ISSUE THREAD

**Issue by rtx3030** [CiaraStrawberry/TemporalKit#104]
when i installed temporalkit and restarted a1111 i got this error

from tqdm.auto import tqdm as old_tqdm
ModuleNotFoundError: No module named 'tqdm.auto'

from what i can see this error is caused by the newer version of tqdm.

i read a tread on github about people having the same issue, i tryed all of there fixes but they do not seem to work.
they mention installing tqdm version 4.57.0 but it does not seem to work for me, maybe i am doing somthing wrong 
url to the tread: https://discuss.huggingface.co/t/sd-auto-1111-no-module-named-tqdm-auto/49659/13 

i am running under a vm of linux mint with a nvidia titan v and 16gb of ram
i did all of the sudo apt update / upgrade and the git pull stuff already

if anyone know a fix to this issue please let me know

**Comment by cocomine** [comment]
Because the dependency currently used by this plug-in uses an old version of tqdm, an error occurs. The short-term solution is to manually install a new version(4.66.1) of tqdm.

`pip install tqdm==4.66.1`

> https://discuss.huggingface.co/t/sd-auto-1111-no-module-named-tqdm-auto/49659/8
> Enter venv according to the mentioned instructions.

**Comment by rtx3030** [comment]
Hello, it worked but i needed to install 4.57.0
version 4.66.1 does not seem to work.

for anyone that has the same problem i am going to pose the solution because it is different in linux 

python -m venv /home/stablediffusion/git/stable-diffusion-webui/venv/
virtualenv activate
source /home/stablediffusion/git/stable-diffusion-webui/venv/bin/activate
pip install tqdm==4.57.0

EXPECTED OUTPUT:

stablediffusion@stablediffusion:~/git/stable-diffusion-webui/venv/bin$ source /home/stablediffusion/git/stable-diffusion-webui/venv/bin/activate
(venv) stablediffusion@stablediffusion:~/git/stable-diffusion-webui/venv/bin$ pip install tqdm==4.57.0
Collecting tqdm==4.57.0
  Using cached tqdm-4.57.0-py2.py3-none-any.whl (72 kB)
Installing collected packages: tqdm
  Attempting uninstall: tqdm
    Found existing installation: tqdm 4.11.2
    Uninstalling tqdm-4.11.2:
      Successfully uninstalled tqdm-4.11.2
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
rembg 2.0.38 requires asyncer>=0.0.2, which is not installed.
rembg 2.0.38 requires filetype>=1.2.0, which is not installed.
rembg 2.0.38 requires imagehash>=4.3.1, which is not installed.
rembg 2.0.38 requires opencv-python-headless>=4.6.0.66, which is not installed.
rembg 2.0.38 requires watchdog>=2.1.9, which is not installed.
rembg 2.0.38 requires tqdm>=4.64.1, but you have tqdm 4.57.0 which is incompatible.
moviepy 0.2.3.2 requires tqdm==4.11.2, but you have tqdm 4.57.0 which is incompatible.
Successfully installed tqdm-4.57.0

**Comment by rtx3030** [comment]
never mind version 4.66.1 seem to work find i think i did something wrong the first time

**Comment by cocomine** [comment]
Glad to hear you had success, remember to mark the issue as closed, thanks.

**Comment by Levine-EVA** [comment]
My TemporalKit isn't showed in my sd, don't know why

**Comment by fenixlam** [comment]
After installing the tqdm==4.66.1 still not working. 
I try to get in venv site-package to kill all tqdm.auto but libraries will be missed. No luck...

**Comment by somnus-21** [comment]
同样的操作，我的视频是720*1280的，因为显卡不够，用TemporalKit第一步生成关键帧的时候选择360*640，生成后也批量图生图了，为什么到TemporalKit的预处理这一步后，我的数字文件夹下的keys目录没有图片呢？请教，

**Comment by cocomine** [comment]
I've fixed it but since I don't have direct access to this repository, you can temporarily use my forked version https://github.com/cocomine/TemporalKit. 
Once I've fully tested it and confirmed it's ok I will open a pull request. If you encounter any problems using my forked version, please submit an issue at https://github.com/cocomine/TemporalKit/issues/new/choose.

**Comment by joshuachung** [comment]
Does not for me:

```
 pip install tqdm==4.66.1
Collecting tqdm==4.66.1
  Downloading tqdm-4.66.1-py3-none-any.whl.metadata (57 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 57.6/57.6 kB 129.1 kB/s eta 0:00:00
Downloading tqdm-4.66.1-py3-none-any.whl (78 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 78.3/78.3 kB 388.2 kB/s eta 0:00:00
Installing collected packages: tqdm
  Attempting uninstall: tqdm
    Found existing installation: tqdm 4.65.0
    Uninstalling tqdm-4.65.0:
      Successfully uninstalled tqdm-4.65.0
Successfully installed tqdm-4.66.1
(base) joshua@M3-Max-MacBook-Pro stable-diffusion-webui % cd ~/stable-diffusion-webui;./webui.sh

################################################################
Install script for stable-diffusion + Web UI
Tested on Debian 11 (Bullseye), Fedora 34+ and openSUSE Leap 15.4 or newer.
################################################################

################################################################
Running on joshua user
################################################################

################################################################
Repo already cloned, using it as install directory
################################################################

################################################################
Create and activate python venv
################################################################

################################################################
Launching launch.py...
################################################################
Python 3.10.14 (main, Mar 19 2024, 21:46:16) [Clang 15.0.0 (clang-1500.3.9.4)]
Version: v1.9.4
Commit hash: feee37d75f1b168768014e4634dcb156ee649c05
Launching Web UI with arguments: --skip-torch-cuda-test --upcast-sampling --no-half-vae --use-cpu interrogate
Traceback (most recent call last):
  File "/Users/joshua/stable-diffusion-webui/launch.py", line 48, in <module>
    main()
  File "/Users/joshua/stable-diffusion-webui/launch.py", line 44, in main
    start()
  File "/Users/joshua/stable-diffusion-webui/modules/launch_utils.py", line 465, in start
    import webui
  File "/Users/joshua/stable-diffusion-webui/webui.py", line 13, in <module>
    initialize.imports()
  File "/Users/joshua/stable-diffusion-webui/modules/initialize.py", line 23, in imports
    import gradio  # noqa: F401
  File "/Users/joshua/stable-diffusion-webui/venv/lib/python3.10/site-packages/gradio/__init__.py", line 3, in <module>
    import gradio.components as components
  File "/Users/joshua/stable-diffusion-webui/venv/lib/python3.10/site-packages/gradio/components/__init__.py", line 1, in <module>
    from gradio.components.annotated_image import AnnotatedImage
  File "/Users/joshua/stable-diffusion-webui/venv/lib/python3.10/site-packages/gradio/components/annotated_image.py", line 8, in <module>
    from gradio_client.documentation import document, set_documentation_group
  File "/Users/joshua/stable-diffusion-webui/venv/lib/python3.10/site-packages/gradio_client/__init__.py", line 1, in <module>
    from gradio_client.client import Client
  File "/Users/joshua/stable-diffusion-webui/venv/lib/python3.10/site-packages/gradio_client/client.py", line 24, in <module>
    from huggingface_hub import CommitOperationAdd, SpaceHardware, SpaceStage
  File "/Users/joshua/stable-diffusion-webui/venv/lib/python3.10/site-packages/huggingface_hub/__init__.py", line 503, in __getattr__
    submod = importlib.import_module(submod_path)
  File "/opt/homebrew/Cellar/python@3.10/3.10.14/Frameworks/Python.framework/Versions/3.10/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/Users/joshua/stable-diffusion-webui/venv/lib/python3.10/site-packages/huggingface_hub/hf_api.py", line 47, in <module>
    from tqdm.auto import tqdm as base_tqdm
ModuleNotFoundError: No module named 'tqdm.auto'
```

**Comment by IpelaTech** [comment]
To solve, I ran 

```
sudo apt install python3-tqdm
```

[source](https://stackoverflow.com/a/77072777)

**Comment by Dogath** [comment]
My SD version is 1.9.4, and I followed the steps to successfully start WebUI after installing Temporal Kit, but it's not shown in the WebUI, it says
ImportError: cannot import name 'create_sampler_and_steps_selection' from 'modules.ui' (D:\stable-diffusion-webui\modules\ui.py)
