### ISSUE TITLE
EBSYNTH DOES NOT REGISTER THE KEYFRAMES IF YOU USE ABOVE 20

### ISSUE THREAD

**Issue by Ethan2018T1** [CiaraStrawberry/TemporalKit#109]
I notice there is an note "EBSYNTH DOES NOT REGISTER THE KEYFRAMES IF YOU USE ABOVE 20,",I confuse want you mean "20", what version？

**Comment by Lucchirsa** [comment]
You can't have use more than 20 keyframes in Ebsynth. If you have more they won't show up

**Comment by CiaraStrawberry** [comment]
yeah what Lucchirsa said  it just wont show up in the UI when you try and link the folders, not much i can do sadly.
