### ISSUE TITLE
how do you apply controlnet after the preprocesing?

### ISSUE THREAD

**Issue by segalinc** [CiaraStrawberry/TemporalKit#12]
Hei there,
thanks a lot for this cool extension!
I watched your quick tutorial but not super clear after the preprocessing when you send to img2img how you use controlnet to transfer the style?
thanks @CiaraStrawberry

**Comment by CiaraStrawberry** [comment]
Hi!
Have you installed the controlnet extension? you should just be able to use it as you would when using img2img normally, i recommend using the hed model

**Comment by segalinc** [comment]
Yes i have. The unclear part is what input do I use on the controlnet side.
The same image with the plates?
Thanks

**Comment by CiaraStrawberry** [comment]
Yes! You can just leave the input black and let it read from currently generating plates, make sure to set the processor resolution to 1024ish, i recommend hed

**Comment by CiaraStrawberry** [comment]
*blank not black lol

**Comment by segalinc** [comment]
Ah perfect then
I'll try this soon
Thanks
