### ISSUE TITLE
suggestion

### ISSUE THREAD

**Issue by xyzDist** [CiaraStrawberry/TemporalKit#19]
Hi CiaraStrawberry! thanks for this amazing extension! I loved it.
not a issue, but 1 question and suggestion.
is the "out_XXX" folder suppose to be put it inside "result"? if not, may I suggest that? I am not sure result folder is for, since it is empty.

suggestion:
I keep re-run the process of "prepare ebysnth", because I update new input looks, but the frames is just keep re-generate and it is actually I don't need it to. What do you think if we could have a toggle in the UI to turn the frames generation on or off, thanks!!

**Comment by xyzDist** [comment]
please ignore my "out_XXX" folders, I realized that is from EbSynth.
I do hitting issue, if I have too many keyframes, EBSynth autofill just does'nt works. even when it works, the UI doesn't have scrolling bar which I couldn't even able to click the "run all" button. Does you hitting this?

**Comment by xyzDist** [comment]
as long as it is automate putting into different batch ketframes folder, it will already helps a lot!
looking forward for you new updates!

the other question, what do you think if we could have toggle to skip the generate frames, if I already have those frames generated.

**Comment by alexfredo** [comment]
I can't wait for the update too !

**Comment by CiaraStrawberry** [comment]
I agree about the need to skip generated frames, that's on my list ^^
