### ISSUE TITLE
TypeError: Cannot handle this data type: (1, 1), <i8

### ISSUE THREAD

**Issue by camenduru** [CiaraStrawberry/TemporalKit#2]
Hi 👋 thanks for the project ❤ I am trying with colab but I got this error I tried to fix it with this https://github.com/CiaraStrawberry/TemporalKit/compare/main...camenduru:TemporalKit:dev but I broke it 😭

https://user-images.githubusercontent.com/54370274/231808354-5c1ba358-0605-4b2c-b452-c68288acc478.mp4

python 3.9.16
torch 2.0.0+cu118
numpy 1.23.3
opencv-python 4.7.0.72

```py
reading video file... /tmp/afca6aee67473a05bb869e8ff86637b542acb258/Untitled.mp4
90
Number of batches: 9
90
Downloading: "https://download.pytorch.org/models/raft_large_C_T_SKHT_V2-ff5fadd5.pth" to /content/stable-diffusion-webui/extensions/SadTalker/checkpoints/hub/checkpoints/raft_large_C_T_SKHT_V2-ff5fadd5.pth
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/PIL/Image.py", line 3080, in fromarray
    mode, rawmode = _fromarray_typemap[typekey]
KeyError: ((1, 1), '<i8')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/gradio/routes.py", line 394, in run_predict
    output = await app.get_blocks().process_api(
  File "/usr/local/lib/python3.9/dist-packages/gradio/blocks.py", line 1075, in process_api
    result = await self.call_function(
  File "/usr/local/lib/python3.9/dist-packages/gradio/blocks.py", line 884, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/usr/local/lib/python3.9/dist-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/usr/local/lib/python3.9/dist-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/usr/local/lib/python3.9/dist-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "/content/stable-diffusion-webui/extensions/TemporalKit/scripts/sd-TemporalKit-UI.py", line 64, in apply_image_to_video
    return berry.process_video_single(video_path=video,fps=fps,per_side=per_side,batch_size=batch_size,fillindenoise=0,edgedenoise=0,_smol_resolution=output_resolution,square_texture=image)
  File "/content/stable-diffusion-webui/extensions/TemporalKit/scripts/Berry_Method.py", line 269, in process_video_single
    processed_frames = process_video(frames,fps,batch_size,fillindenoise,edgedenoise,_smol_resolution,square_texture)
  File "/content/stable-diffusion-webui/extensions/TemporalKit/scripts/Berry_Method.py", line 377, in process_video
    processed_batch,all_flow_after = sdprocess.batch_sd_run(encoded_batch, encoded_new_frame, frame_count, seed, False, fillindenoise, edgedenoise, _smol_resolution,True,encoded_new_frame,False)
  File "/content/stable-diffusion-webui/extensions/TemporalKit/scripts/stable_diffusion_processing.py", line 268, in batch_sd_run
    result,mask,flow = prepare_request(allpaths,i,output_images[i-1],smol_resolution,seed,last_mask,last_last_mask,fillindenoise,edgedenoise,target,diffuse,Forwards)
  File "/content/stable-diffusion-webui/extensions/TemporalKit/scripts/stable_diffusion_processing.py", line 93, in prepare_request
    warped_path,flow,unused_mask,whitepixels,flow_img = raft.apply_flow_based_on_images(allpaths[index - 1],allpaths[index],last_stylized,resolution,index,temp_folder)
  File "/content/stable-diffusion-webui/extensions/TemporalKit/scripts/optical_flow_raft.py", line 134, in apply_flow_based_on_images
    warped_image,unused_mask,white_pixels = apply_flow_to_image_with_unused_mask(provided_image,predicted_flow)
  File "/content/stable-diffusion-webui/extensions/TemporalKit/scripts/optical_flow_raft.py", line 276, in apply_flow_to_image_with_unused_mask
    mask = utilityb.create_hole_mask(flow)
  File "/content/stable-diffusion-webui/extensions/TemporalKit/scripts/berry_utility.py", line 267, in create_hole_mask
    toblur = Image.fromarray(expanded).convert('L')
  File "/usr/local/lib/python3.9/dist-packages/PIL/Image.py", line 3083, in fromarray
    raise TypeError(msg) from e
TypeError: Cannot handle this data type: (1, 1), <i8
```

**Comment by CiaraStrawberry** [comment]
Hi! Sounds like something to do with the input image format or the inference isn't running correctly, can you upload the video you tested this with?

**Comment by camenduru** [comment]
https://files.catbox.moe/72bsm9.mp4

**Comment by JustCaptcha** [comment]
Have the same issue. I'm running locally.

**Comment by JetsonNanoKit** [comment]
I also ran into this issue, which shows that this problem is not accidental, by the way, there are a lot of bugs in your scripts, can you fully test it before opening it up?

**Comment by JetsonNanoKit** [comment]
> Hi! Sounds like something to do with the input image format or the inference isn't running correctly, can you upload the video you tested this with?

I also ran into this issue, which shows that this problem is not accidental, by the way, there are a lot of bugs in your scripts, can you fully test it before opening it up?

**Comment by kliyer-ai** [comment]
Having the same issue with this video: https://github.com/showlab/Tune-A-Video/blob/main/data/man-surfing.mp4

**Comment by CiaraStrawberry** [comment]
Il.be brainstorming the potential issue here myself on Sunday, seems like an edge case of some kind, what os are people running into this on?

**Comment by camenduru** [comment]
![image](https://user-images.githubusercontent.com/54370274/232197491-2fbc4c54-654f-4b5a-bca3-827768af4274.png)

**Comment by camenduru** [comment]
And
```
Edition	Windows 10
Version	22H2
OS build	19045.2846
```

**Comment by jinnsp** [comment]
I just created a PR (#5 ). It might fix this issue.
Can you take a look at the changes and see if it helps?

**Comment by jinnsp** [comment]
Here's what I found.
When `flow_map` contains only slightly shifted values, it results in a sparse `hole_mask`, causing `whitepixels` to be 0. This eventually leads to the path of the warped image being passed to `base64_to_texture` instead of the byte string.

you can try the following quick hack:
<h5 a><strong><code>scripts/berry_utility.py</code></strong></h5>

```python
# change code like this
if base64_string.lower().endswith('png'):
    image = Image.open(base64_string)
else:
    decoded_data = base64.b64decode(base64_string)
    buffer = BytesIO(decoded_data)
    image = Image.open(buffer)
```
(As I skimmed through the code, please be aware that this is just a quick hack and may not address the underlying issue completely.)


Additionally, please update the line:
```grayscale_mask = np.where(conv_result >= threshold, int(255 * grayscale_intensity), 0)``` 
to
```grayscale_mask = np.where(conv_result >= threshold, int(255 * grayscale_intensity), 0).astype(np.uint8)```
This change will ensure that uint8 type is always returned.

**Comment by camenduru** [comment]
thanks @jinnsp ❤

**Comment by camenduru** [comment]
🥳

https://user-images.githubusercontent.com/54370274/232255742-3e166db2-5bd3-44bc-991e-fdc54caaffad.mp4

**Comment by CiaraStrawberry** [comment]
Thanks for the fix!

c# brain, used to hardcoded variables, need to start setting them when i write Python code aha.

I'll be closing this now if that's everything for this specific issue.
