### ISSUE TITLE
Please can you explain how you generate for example a 30sec video with EBsynth 

### ISSUE THREAD

**Issue by alexfredo** [CiaraStrawberry/TemporalKit#23]
Hi I have installed successfully the latest version, and I want to know what is the best method for generate a long video with EBsynth ? Also thanks for this amazing extension !

**Comment by CiaraStrawberry** [comment]
I'm making a full length video on it later, but for the abbreviated version:

use these settings and drop your video in the video bit on the left

![image](https://user-images.githubusercontent.com/13116982/234342905-d5690142-3a5c-42a1-bcc4-1276ea5efd1a.png)

go to the newly generated input folder in your specified folder, run the results with the img2img batch tab as you would with any folder and put the output as the output folder in the same directory, make sure to use lineart controlnet and 0.3-0.5 denoise

then go to the temporal kit, ebsynth process tab, paste the folder location and click read last settings, click "prepare ebsynth" after that is done, go into each of the numbered folders and with a new ebsynth window click the keys and the frames folders and run it.

then click recombine ebsynth button and voila

it's a bit of a list so the full video will be later ^^

**Comment by alexfredo** [comment]
Ok I will try these settings ! thx

**Comment by CiaraStrawberry** [comment]
boop: https://www.youtube.com/watch?v=z3YNHiuvxyg&ab_channel=CiaraRowles
