### ISSUE TITLE
Error running TemporalKit in Google Colab with FFMPEG 4.2.7 (fast_stable_diffusion_AUTOMATIC1111.ipynb)

### ISSUE THREAD

**Issue by okeymmloo** [CiaraStrawberry/TemporalKit#24]
Hello,

I have been trying to use TemporalKit in Google Colab using the fast_stable_diffusion_AUTOMATIC1111.ipynb notebook. But I am getting an error when I try to execute the function. I have installed FFMPEG 4.2.7 and have checked that the version is up to date. However, when running the program, I am getting the following error:
OSError: MoviePy error: failed to read the first frame of video file /tmp/tmpcf8i8e_y.mp4. That might mean that the file is corrupted. That may also mean that you are using a deprecated version of FFMPEG. On Ubuntu/Debian for instance the version in the repos is deprecated. Please update to a recent version from the website.

I have Verified the following, the video file path is correct and the video file is not corrupted.

I haven't found any bugs in the code that might be causing problems rendering the video.

**Comment by CiaraStrawberry** [comment]
I have found some video simply give that kind of error no matter what you do with them, try it with some stock video and see if that works, otherwise, it's some ffmpeg issue on notebook which would be quite a bit harder to diagnose.

**Comment by merodiro** [comment]
Try running this. it fixed it for me on ubuntu
```
!pip uninstall moviepy
!pip install moviepy==2.0.0.dev2
```

**Comment by okeymmloo** [comment]
thanks at last I was able, because it failed me with all the videos and I updated the moviepy and it works, now to see tutorials on how to use it ;)

**Comment by Johnwolf83** [comment]
is there a chance to get the colab notebook used for this??

**Comment by okeymmloo** [comment]
Yes, I use the AUTOMATIC1111 colab and before executing the last cell "Start Stable-Diffusion" I execute this code:

!pip uninstall moviepy
!pip install moviepy==2.0.0.dev2

pip install scenedetect[opencv]

**Comment by Johnwolf83** [comment]
> !pip uninstall moviepy !pip install moviepy==2.0.0.dev2
> 
> pip install scenedetect[opencv]

The FFMPEG is installed on the same colab instance?

**Comment by okeymmloo** [comment]
I don't remember that part, I know that when I run it for the first time I used the command to run !pip install python-ffmpeg but then I didn't use it again I just always run before starting
!pip uninstall moviepy
!pip install moviepy==2.0.0.dev2

pip install scenedetect[opencv]
