### ISSUE TITLE
Pre=-Processing Batch Error - IndexError: list index out of range

### ISSUE THREAD

**Issue by chnl** [CiaraStrawberry/TemporalKit#29]
stable-diffusion-webui-master\extensions\TemporalKit\scripts\sd-TemporalKit-UI.py", line 122, in preprocess_video
    processed = image[0]
IndexError: list index out of range

**Comment by merodiro** [comment]
I had this issue when using `-1`. setting a number fixed it for me

**Comment by helloasv** [comment]
I had tick SplitVideo and Split based on cuts(as well),I fixed it.hope this helps.

**Comment by CiaraStrawberry** [comment]
Fixed both these issues just now, my apologies for the bugs.
