### ISSUE TITLE
All keyframes are identical

### ISSUE THREAD

**Issue by philipmiesbauer** [CiaraStrawberry/TemporalKit#41]
I am processing a video with 29.97 FPS 1080x1920 (portrait mode)

WHen I press run it generates the right amount of keyframes, but they are all identical.

Any idea what the issue could be?

**Comment by CiaraStrawberry** [comment]
What's your frames per keyframe value? are you using split frames?

**Comment by orfeaus** [comment]
I'm also seeing this issue with all frames being identical.

6 frames per keyframe at 24fps.

**Comment by unlagi** [comment]
I also have the problem , all frames are identical , i've tried serveral setting about frame/frame per keys/grid.

Installed full build FFMPEG ,using firefox browser

**Comment by unlagi** [comment]
![2023-05-06 15_07_28-StableDiffusion](https://user-images.githubusercontent.com/129839378/236612201-997b0677-af5e-40c0-8998-101ad2217894.png)

**Comment by vsewall** [comment]
yep, same problem. and I am sure that the reason is in fps=29.97.
as soon as I changed it in the original video to 30, the grids began to look ok

**Comment by CiaraStrawberry** [comment]
should be fixed now ^^
