### ISSUE TITLE
Standalone script

### ISSUE THREAD

**Issue by AmanKishore** [CiaraStrawberry/TemporalKit#46]
Hi! Have you worked on a standalone script for this that does not use Auto1111?

**Comment by CiaraStrawberry** [comment]
Hi! nop, don't really see a huge need to as the main benefits of using it outside of automatic111 are discounted by ebsynth anyway, i should probably hook it up to the API at some point mind you.

**Comment by AmanKishore** [comment]
Ah ok, do you know if there are any good scripts for ebsynth?

**Comment by CiaraStrawberry** [comment]
None i've seen i'm afraid, there's no official interface but someone somewhere has probably hacked something together lol
