### ISSUE TITLE
Automatic1111 :  interface display problem on full screen

### ISSUE THREAD

**Issue by StudioDUzes** [CiaraStrawberry/TemporalKit#64]
Windows 11 - Chrome - screen 1920 x 1080

![capture 1](https://github.com/CiaraStrawberry/TemporalKit/assets/131154500/3f5076b5-cc28-448c-a126-b3217a5d2c61)
![capture 2](https://github.com/CiaraStrawberry/TemporalKit/assets/131154500/69fecbc8-3dc4-419a-8254-e750c377c8ba)

A simple and useful extension, thank you

**Comment by alexbofa** [comment]
`Stable-Diffusion\extensions\TemporalKit\style.css` or `Stable-Diffusion\user.css`
add this code:
```
video.svelte-1vnmhm4 {
    max-height: 500px;
}
```
![image](https://github.com/CiaraStrawberry/TemporalKit/assets/58225118/433455f6-d559-4a1a-ac15-74018d670044)

**Comment by StudioDUzes** [comment]
> `Stable-Diffusion\user.css` add this code:
> 
> ```
> video.svelte-1vnmhm4 {
>     max-height: 500px;
> }
> ```
> 
> ![image](https://user-images.githubusercontent.com/58225118/257834227-433455f6-d559-4a1a-ac15-74018d670044.png)

Thank you very much
