### ISSUE TITLE
[Not Bug] What is this extension for?

### ISSUE THREAD

**Issue by amiremami** [CiaraStrawberry/TemporalKit#9]
Hi. Sorry, I didn't understand what this script does, can you explain a bit, is there any tutorial? 

Thanks

**Comment by alexfredo** [comment]
It's adding temporal "stability", because by default the pictures is really unstable when we generate video with stable diffusion.

**Comment by alexfredo** [comment]
Tutorial single batch here https://twitter.com/CiaraRowles1/status/1645923461343363072
And a batch demonstration here:
https://mobile.twitter.com/CiaraRowles1/status/1646458056803250178

**Comment by amiremami** [comment]
Thanks a lot, I'm noob at this plugin and trying it to see what the outcome will be. In my first test, I got this error:

![image](https://user-images.githubusercontent.com/15929497/232795222-8d190848-cd27-4145-8bc6-eafef5c31f51.png)

**Comment by CiaraStrawberry** [comment]
Perfect, thanks for letting us know how you fixed that.
